# Generated by Django 4.1.7 on 2023-11-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('result', models.TextField()),
                ('analyzed_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
