# Generated by Django 4.1.7 on 2023-11-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='model_choice',
            field=models.CharField(default='Default Model', max_length=100),
        ),
        migrations.AddField(
            model_name='news',
            name='vector_choice',
            field=models.CharField(default='Default Vector', max_length=100),
        ),
    ]
